name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVELOP_SERVER_IP }}
          port: 22
          username: ${{ secrets.DEVELOP_SERVER_USERNAME }}
          key: ${{ secrets.DEVELOP_SSH_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo ps -ef | grep java | grep -v grep | awk '{print $2}' | sudo xargs kill -9
            sudo rm -rf KDT_Y_BE_Mini-Project/
            git clone https://github.com/Dont12/KDT_Y_BE_Mini-Project.git
            cd KDT_Y_BE_Mini-Project/
            echo "${{ secrets.DEVELOP_APPLICATION_YML }}" > ./src/main/resources/application.yml
            sudo cp ../keystore.p12 ./src/main/resources
            sudo ./gradlew build
            sudo nohup ./gradlew bootRun > nohup.out 2> nohup.err < /dev/null &